In [1]:
import duckdb

con = duckdb.connect("developer_project.duckdb")

HELLO!

### Table for `DEVPM_8674_Cal_Poly_Export_dev_activity.csv`

In [2]:


con.execute("""
CREATE TABLE activity_raw AS
SELECT *
FROM read_csv_auto(
    'DEVPM_8674_Cal_Poly_Export_dev_activity.csv',
    delim='|',
    header=True,
    all_varchar=True,
    sample_size=-1
)
""")

con.execute("""
CREATE TABLE activity_clean AS
SELECT
    dev_contact,
    activity,
    activity_name,
    activity_type,
    activity_role,
    activity_attendance,
    TRY_CAST(activity_score AS DOUBLE) AS activity_score,
    TRY_CAST(activity_date AS TIMESTAMP) AS activity_date,
    activity_id
FROM activity_raw
""")

100% ▕██████████████████████████████████████▏ (00:00:20.44 elapsed)
100% ▕██████████████████████████████████████▏ (00:00:05.97 elapsed)

In [3]:
con.execute("DESCRIBE activity_clean").fetchdf()

           column_name column_type null   key default extra
0          dev_contact     VARCHAR  YES  None    None  None
1             activity     VARCHAR  YES  None    None  None
2        activity_name     VARCHAR  YES  None    None  None
3        activity_type     VARCHAR  YES  None    None  None
4        activity_role     VARCHAR  YES  None    None  None
5  activity_attendance     VARCHAR  YES  None    None  None
6       activity_score      DOUBLE  YES  None    None  None
7        activity_date   TIMESTAMP  YES  None    None  None
8          activity_id     VARCHAR  YES  None    None  None

In [4]:
con.execute("SELECT COUNT(*) FROM activity_raw").fetchdf()

   count_star()
0      69347526

In [4]:
con.execute("SELECT DISTINCT activity_name FROM activity_raw").fetchdf()

                                            activity_name
0                                                 TRELLIS
1                                  Nemotron-4-340B-Reward
2             NVIDIA Retrieval QA Mistral 4B Reranking v3
3                   SR-IOV Network Operator Config Daemon
4                                    NVIDIA LiveCodeBench
...                                                   ...
231251  AI & Data Science: TensorRT: Fail to convert p...
231252  AI & Data Science: TensorRT: Unstable inferenc...
231253  Robotics & Edge Computing: Jetson Orin NX: Jet...
231254  Robotics & Edge Computing: Isaac ROS: Stereo C...
231255  AI & Data Science: Computer Vision & Image Pro...

[231256 rows x 1 columns]

In [5]:
con.execute("SELECT DISTINCT activity_type FROM activity_raw").fetchdf()

         activity_type
0                 Quiz
1               Opt In
2   Event Registration
3               NVINFO
4             Approved
..                 ...
59           Container
60          Conference
61             Contest
62        NV On-Demand
63              remote

[64 rows x 1 columns]

In [8]:
con.execute("SELECT DISTINCT activity_score FROM activity_raw").fetchdf()

   activity_score
0            40.0
1           100.0
2             4.0
3            15.0
4             8.0
5             2.0
6             0.0
7             3.0
8             6.0
9        948905.0
10       949156.0
11           10.0
12            5.0
13           20.0
14            NaN
15       949763.0
16            1.0

In [ ]:
con.execute("""SELECT column_name
FROM information_schema.columns
WHERE table_name = 'activity_raw'""")

### Table for `DEVPM_8674_Cal_Poly_Export_dev_contact.csv`

In [7]:
con.execute("""
CREATE OR REPLACE TABLE contact_raw AS
SELECT *
FROM read_csv_auto(
    'DEVPM_8674_Cal_Poly_Export_dev_contact.csv',
    delim=',',
    header=True,
    all_varchar=True,
    sample_size=-1
)
""")

100% ▕██████████████████████████████████████▏ (00:00:13.54 elapsed)

In [8]:
con.execute("""
CREATE OR REPLACE TABLE contact_clean AS
SELECT
    developer_id,
    program_application_source,
    country,
    region,
    sub_region,
    zone,
    territory,
    organization_english_name,
    development_areas,
    other_development_areas,
    industry_segment_vertical,
    other_industry_segment_vertical,
    sub_industry_segment_vertical,
    fields_of_interest,
    other_fields_of_interest,
    TRY_CAST(first_program_application_date AS TIMESTAMP) AS first_program_application_date,
    account_id,
    account_name,
    TRY_CAST(last_activity_date AS TIMESTAMP) AS last_activity_date,
    TRY_CAST(last_modified_date AS TIMESTAMP) AS last_modified_date,
    TRY_CAST(created_date AS TIMESTAMP) AS created_date,
    wwfo_category,
    wwfo_target_list,
    account_industry_segment,
    account_source,
    account_type,
    TRY_CAST(devzone_last_login_date AS TIMESTAMP) AS devzone_last_login_date,
    organization_website,
    inception_id,
    TRY_CAST(first_activity_date AS TIMESTAMP) AS first_activity_date,
    normalized_account_name,
    TRY_CAST(rdp_exit_date AS TIMESTAMP) AS rdp_exit_date
FROM contact_raw
""")

100% ▕██████████████████████████████████████▏ (00:00:05.57 elapsed)

In [9]:
con.execute("DESCRIBE contact_clean").fetchdf()

                        column_name column_type null   key default extra
0                      developer_id     VARCHAR  YES  None    None  None
1        program_application_source     VARCHAR  YES  None    None  None
2                           country     VARCHAR  YES  None    None  None
3                            region     VARCHAR  YES  None    None  None
4                        sub_region     VARCHAR  YES  None    None  None
5                              zone     VARCHAR  YES  None    None  None
6                         territory     VARCHAR  YES  None    None  None
7         organization_english_name     VARCHAR  YES  None    None  None
8                 development_areas     VARCHAR  YES  None    None  None
9           other_development_areas     VARCHAR  YES  None    None  None
10        industry_segment_vertical     VARCHAR  YES  None    None  None
11  other_industry_segment_vertical     VARCHAR  YES  None    None  None
12    sub_industry_segment_vertical     VARCHAR  YES  None    None  None
13               fields_of_interest     VARCHAR  YES  None    None  None
14         other_fields_of_interest     VARCHAR  YES  None    None  None
15   first_program_application_date   TIMESTAMP  YES  None    None  None
16                       account_id     VARCHAR  YES  None    None  None
17                     account_name     VARCHAR  YES  None    None  None
18               last_activity_date   TIMESTAMP  YES  None    None  None
19               last_modified_date   TIMESTAMP  YES  None    None  None
20                     created_date   TIMESTAMP  YES  None    None  None
21                    wwfo_category     VARCHAR  YES  None    None  None
22                 wwfo_target_list     VARCHAR  YES  None    None  None
23         account_industry_segment     VARCHAR  YES  None    None  None
24                   account_source     VARCHAR  YES  None    None  None
25                     account_type     VARCHAR  YES  None    None  None
26          devzone_last_login_date   TIMESTAMP  YES  None    None  None
27             organization_website     VARCHAR  YES  None    None  None
28                     inception_id     VARCHAR  YES  None    None  None
29              first_activity_date   TIMESTAMP  YES  None    None  None
30          normalized_account_name     VARCHAR  YES  None    None  None
31                    rdp_exit_date   TIMESTAMP  YES  None    None  None

In [10]:
con.execute("SELECT COUNT(*) FROM contact_raw").fetchdf()

   count_star()
0       8903197

In [2]:
con.execute("SELECT * FROM contact_raw LIMIT 10").fetchdf()

,developer_id,program_application_source,country,region,sub_region,zone,territory,organization_english_name,development_areas,other_development_areas,...,wwfo_target_list,account_industry_segment,account_source,account_type,devzone_last_login_date,organization_website,inception_id,first_activity_date,normalized_account_name,rdp_exit_date
0,9828293,dli,India,APAC,India,India,SOUTH ASIA,L&T Technology Services,Agentic AI / Generative AI;Data Science;Roboti...,null,...,null,null,Leadspace;GSI;NV Top 1000 Ent,Enterprise,null,ltts.com,null,2025-11-25T09:30:05.000Z,L&T Technology Services,null
1,9828383,dli,India,APAC,India,India,SOUTH ASIA,L&T Technology Services,Agentic AI / Generative AI;Data Science;Data C...,null,...,null,null,Leadspace;GSI;NV Top 1000 Ent,Enterprise,null,ltts.com,null,2025-11-25T09:41:30.000Z,L&T Technology Services,null
2,9828681,devzone,India,APAC,India,India,SOUTH ASIA,Dayananda Sagar Universiry,Agentic AI / Generative AI;AR / VR;Simulation ...,null,...,null,null,Manual,NaN,2026-03-09T22:22:32.000Z,null,null,2025-11-25T00:00:00.000Z,Not Normalized,null
3,9829013,dli,India,APAC,India,India,SOUTH ASIA,LTTS,Developer Tools & Techniques;Agentic AI / Gene...,null,...,null,null,Manual,NaN,null,null,null,2025-11-25T11:24:35.000Z,Not Normalized,null
4,9829125,devzone,India,APAC,India,India,SOUTH ASIA,Hexaware,Agentic AI / Generative AI;Data Center / Cloud,null,...,null,null,Manual,NaN,2025-12-01T06:12:14.000Z,null,null,2025-11-25T11:34:05.000Z,Not Normalized,null
5,9829190,dli,India,APAC,India,India,SOUTH ASIA,L&T Technology Services,Agentic AI / Generative AI,null,...,null,null,Leadspace;GSI;NV Top 1000 Ent,Enterprise,null,ltts.com,null,2025-11-25T11:46:56.000Z,L&T Technology Services,null
6,9831912,dli,India,APAC,India,India,SOUTH ASIA,LTTS,Agentic AI / Generative AI,null,...,null,null,Manual,NaN,null,null,null,2025-11-26T01:34:57.000Z,Not Normalized,null
7,9832663,null,India,APAC,India,India,SOUTH ASIA,Nokia,null,null,...,SuperPOD 2019_P1,null,Fortune 500: 2020;WWFO; Fortune 500: 2021;Telc...,Enterprise,null,nokia.com,null,2025-12-10T00:00:00.000Z,Nokia,null
8,9833472,dli,India,APAC,India,India,SOUTH ASIA,MLRIT,Trustworthy AI / Cybersecurity;Data Science;Ag...,null,...,null,null,Leadspace,NaN,null,mlrit.ac.in,null,2025-11-26T08:05:31.000Z,Mlrit,null
9,9836934,dli,India,APAC,India,India,SOUTH ASIA,Tejas Networks,Trustworthy AI / Cybersecurity;Data Science;Ne...,null,...,null,null,Manual,NaN,null,null,null,2025-11-27T02:03:26.000Z,Not Normalized,null

### Table for `DEVPM_8674_Cal_Poly_Export_sdk_download.csv`

In [14]:
con.execute("""
CREATE OR REPLACE TABLE sdk_download_raw AS
SELECT *
FROM read_csv_auto(
    'DEVPM_8674_Cal_Poly_Export_sdk_download.csv',
    delim=',',
    header=True,
    all_varchar=True,
    sample_size=-1
)
""")

100% ▕██████████████████████████████████████▏ (00:00:25.55 elapsed)

In [15]:
con.execute("""
CREATE OR REPLACE TABLE sdk_download_clean AS
SELECT
    "source" AS source,
    "sdk_name" AS sdk_name,
    "PRODUCTNAME" AS product_name,
    "PRODUCTRELEASE" AS product_release,
    "country" AS country,
    "region" AS region,
    "subregion" AS subregion,
    "territory" AS territory,
    "zone" AS zone,
    TRY_CAST("downloaddate" AS DATE) AS download_date,
    "FILETYPE" AS file_type,
    "OPERATINGSYSTEM" AS operating_system,
    "OS_DISTRIBUTION" AS os_distribution,
    "ARCHITECTURE" AS architecture,
    TRY_CAST("KPI" AS DOUBLE) AS kpi,
    TRY_CAST("downloadcount" AS BIGINT) AS download_count
FROM sdk_download_raw
""")

100% ▕██████████████████████████████████████▏ (00:00:09.38 elapsed)

In [16]:
con.execute("DESCRIBE sdk_download_clean").fetchdf()

         column_name column_type null   key default extra
0             source     VARCHAR  YES  None    None  None
1           sdk_name     VARCHAR  YES  None    None  None
2       product_name     VARCHAR  YES  None    None  None
3    product_release     VARCHAR  YES  None    None  None
4            country     VARCHAR  YES  None    None  None
5             region     VARCHAR  YES  None    None  None
6          subregion     VARCHAR  YES  None    None  None
7          territory     VARCHAR  YES  None    None  None
8               zone     VARCHAR  YES  None    None  None
9      download_date        DATE  YES  None    None  None
10         file_type     VARCHAR  YES  None    None  None
11  operating_system     VARCHAR  YES  None    None  None
12   os_distribution     VARCHAR  YES  None    None  None
13      architecture     VARCHAR  YES  None    None  None
14               kpi      DOUBLE  YES  None    None  None
15    download_count      BIGINT  YES  None    None  None

In [18]:
con.execute("SELECT COUNT(*) FROM sdk_download_raw").fetchdf()

   count_star()
0      93038213