In [1]:
import duckdb

con = duckdb.connect("developer_project.duckdb")

In [2]:
display(con.execute("SHOW TABLES").fetchdf())

c:\Users\tyler\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

                 name
0      activity_clean
1        activity_raw
2       contact_clean
3         contact_raw
4  sdk_download_clean
5    sdk_download_raw

### Analysis for `DEVPM_8674_Cal_Poly_Export_dev_activity.csv`

In [3]:
con.execute("SELECT COUNT(*) FROM activity_clean").fetchdf()

   count_star()
0      69347526

In [4]:
con.execute("""SELECT column_name
FROM information_schema.columns
WHERE table_name = 'activity_raw'""").fetchdf()

               column_name
0                 activity
1            activity_date
2            activity_name
3            activity_type
4            activity_role
5      activity_attendance
6              dev_contact
7           activity_score
8                 filepath
9              activity_id
10                     pk1
11                     pk2
12             lead_source
13      nvidia_campaign_id
14  gtc_nvidia_campaign_id
15     lead_source_details

In [5]:
con.execute("SUMMARIZE activity_clean").fetchdf()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,column_name,column_type,min,max,approx_unique,avg,std,q25,q50,q75,count,null_percentage
0,dev_contact,VARCHAR,0003027cbcc9f926a435232e311b3a5ffcbb0d16668d12...,fffa9af220d19ab1ad50f0d2b1af409e4b0b0f732481d4...,6971468,NaN,NaN,NaN,NaN,NaN,69347526,0.00
1,activity,VARCHAR,Brev,"timeout-in-us = 4096 * (2**timeout)""",21,NaN,NaN,NaN,NaN,NaN,69347526,0.00
2,activity_name,VARCHAR,(COURSE ENDING ON 7/1/24) High-Performance Com...,（同時通訳付）Unlocking the Power of Agentic AI: Effe...,247536,NaN,NaN,NaN,NaN,NaN,69347526,7.12
3,activity_type,VARCHAR,API Catalog Hosted API,true,59,NaN,NaN,NaN,NaN,NaN,69347526,0.00
4,activity_role,VARCHAR,*Showstopper*,VivaTech Attendee,40,NaN,NaN,NaN,NaN,NaN,69347526,13.20
5,activity_attendance,VARCHAR,15,true,24,NaN,NaN,NaN,NaN,NaN,69347526,81.36
6,activity_score,DOUBLE,0.0,949763.0,16,3.4864210675072056,198.79941555813494,1.2930108278218273,3.0,3.0,69347526,1.31
7,activity_date,TIMESTAMP,2020-01-01 00:00:00,2026-03-12 17:24:45,10083528,2023-07-29 09:29:58.041171,NaN,2021-12-21 02:34:21.2988,2023-10-17 19:53:38.379177,2025-04-04 18:35:19.278219,69347526,0.00
8,activity_id,VARCHAR,--06jdo1meBBcl3t43Bw8twy5qo4b-WOFu9r_NPZ5JQ_20...,zzzKQIQtKhEv-aG9Dqw60fJX5IV8Rr8rrCGRIWBmS50_20...,51295433,NaN,NaN,NaN,NaN,NaN,69347526,0.00
9,filepath,VARCHAR,!git clone https://github.com/NVIDIA-AI-Bluepr...,zwn4k2csbt9r/nvcf/punctuation-riva,210473,NaN,NaN,NaN,NaN,NaN,69347526,22.16
10,pk1,VARCHAR,--06jdo1meBBcl3t43Bw8twy5qo4b-WOFu9r_NPZ5JQ_20...,zzzKQIQtKhEv-aG9Dqw60fJX5IV8Rr8rrCGRIWBmS50_20...,51295433,NaN,NaN,NaN,NaN,NaN,69347526,0.00
11,pk2,VARCHAR,0000041377580f8fc27178c22a964725,zzr7dxtb,368697,NaN,NaN,NaN,NaN,NaN,69347526,0.17
12,lead_source,VARCHAR,$direct,yseo,529,NaN,NaN,NaN,NaN,NaN,69347526,82.81
13,nvidia_campaign_id,VARCHAR,%20%20%20em-even-981938-hats3th_vi_na_all_s4%2...,—43656,26733,NaN,NaN,NaN,NaN,NaN,69347526,98.99
14,gtc_nvidia_campaign_id,VARCHAR,em-anno-951875,so-medi-691956,46,NaN,NaN,NaN,NaN,NaN,69347526,100.00
15,lead_source_details,VARCHAR,%22NVODIA+developer%22,zhidao.baidu.com/question/49345313.html?fr=iks...,177729,NaN,NaN,NaN,NaN,NaN,69347526,84.02

In [6]:
con.execute("""
SELECT activity_name, COUNT(*) AS count
FROM activity_raw
GROUP BY activity_name
ORDER BY count DESC
""").fetchdf()

                                            activity_name     count
0                                             JetPack SDK  10316702
1                                                   cuDNN   8242287
2                                                 jetpack   7365167
3                                               Developer   6527784
4                                                     NaN   4940143
...                                                   ...       ...
231251  Technical Blogs & Events: Technical Blog: Upco...         1
231252                                         CGX Server         1
231253                             test-feature-container         1
231254  GPU Unix Graphics: Linux: X11 on an optimus sy...         1
231255                                   rapids-with-port         1

[231256 rows x 2 columns]

In [7]:
con.execute("""
SELECT activity_type, COUNT(*) AS count
FROM activity_clean
GROUP BY activity_type
ORDER BY count DESC
""").fetchdf()

             activity_type     count
0                Installer  36999321
1                 Approved   6654555
2   API Catalog Hosted API   6466203
3                Container   5345238
4            Documentation   1791479
..                     ...       ...
59                   image         3
60                    true         3
61                     NaN         3
62                  NVINFO         2
63                Document         2

[64 rows x 2 columns]

In [8]:
con.execute("""
SELECT activity_score, COUNT(*) AS count
FROM activity_clean
GROUP BY activity_score
ORDER BY count DESC
""").fetchdf()

    activity_score     count
0              3.0  40386220
1              1.0  10136402
2              0.0   7304120
3              5.0   5173631
4             10.0   1907972
5             20.0   1435932
6              NaN    906358
7              6.0    635828
8              4.0    569597
9             40.0    498176
10             2.0    150807
11             8.0    143233
12            15.0     77497
13           100.0     21750
14        949763.0         1
15        949156.0         1
16        948905.0         1

In [9]:
con.execute("""
SELECT dev_contact, COUNT(*) AS count
FROM activity_clean
GROUP BY dev_contact
ORDER BY count DESC
""").fetchdf()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

        dev_contact    count
0           5903679  2027375
1           5886356   789400
2           3931685   187095
3           1303597   151947
4           2028858   142980
...             ...      ...
7660274     3384526        1
7660275    10332902        1
7660276    10559025        1
7660277     8559770        1
7660278     7041628        1

[7660279 rows x 2 columns]

In [10]:
# Check duplicates (replace with primary key if known)
display(con.execute("""
SELECT 
    COUNT(*) AS total_rows,
    COUNT(*) - (
        SELECT COUNT(*)
        FROM (SELECT DISTINCT * FROM activity_clean)
    ) AS duplicate_rows
FROM activity_clean
""").fetchdf())

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   total_rows  duplicate_rows
0    69347526          163735

### Analysis for `DEVPM_8674_Cal_Poly_Export_dev_contact.csv`

In [11]:
con.execute("SELECT COUNT(*) FROM contact_clean").fetchdf()

   count_star()
0       8903197

In [12]:
con.execute("SELECT DISTINCT developer_id FROM contact_clean").fetchdf()

        developer_id
0            7860513
1            8615958
2            4015643
3            6198961
4            6487782
...              ...
8903192      7721853
8903193      7720032
8903194      9184609
8903195      6239920
8903196      7276802

[8903197 rows x 1 columns]

In [13]:
con.execute("""SELECT column_name
FROM information_schema.columns
WHERE table_name = 'contact_clean'""").fetchdf()

                        column_name
0                      developer_id
1        program_application_source
2                           country
3                            region
4                        sub_region
5                              zone
6                         territory
7         organization_english_name
8                 development_areas
9           other_development_areas
10        industry_segment_vertical
11  other_industry_segment_vertical
12    sub_industry_segment_vertical
13               fields_of_interest
14         other_fields_of_interest
15   first_program_application_date
16                       account_id
17                     account_name
18               last_activity_date
19               last_modified_date
20                     created_date
21                    wwfo_category
22                 wwfo_target_list
23         account_industry_segment
24                   account_source
25                     account_type
26          devzone_last_login_date
27             organization_website
28                     inception_id
29              first_activity_date
30          normalized_account_name
31                    rdp_exit_date

In [14]:
con.execute("SUMMARIZE contact_clean").fetchdf()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,column_name,column_type,min,max,approx_unique,avg,std,q25,q50,q75,count,null_percentage
0,developer_id,VARCHAR,0001bf3476c2cef05eca00ff79c57f5b86702a1f947548...,fffd473b66da19a680630437ec69aa8c7e450e2cec7848...,8959896,NaN,<NA>,NaN,NaN,NaN,8903197,0.00
1,program_application_source,VARCHAR,GTC,vcalliance,16,NaN,<NA>,NaN,NaN,NaN,8903197,0.00
2,country,VARCHAR,Afghanistan,null,270,NaN,<NA>,NaN,NaN,NaN,8903197,0.00
3,region,VARCHAR,APAC,null,4,NaN,<NA>,NaN,NaN,NaN,8903197,0.00
4,sub_region,VARCHAR,Africa,null,13,NaN,<NA>,NaN,NaN,NaN,8903197,0.00
5,zone,VARCHAR,ANZ,null,21,NaN,<NA>,NaN,NaN,NaN,8903197,0.00
6,territory,VARCHAR,AFRICA,null,18,NaN,<NA>,NaN,NaN,NaN,8903197,0.00
7,organization_english_name,VARCHAR,Babaground,󠀡󠀡,1665680,NaN,<NA>,NaN,NaN,NaN,8903197,0.00
8,development_areas,VARCHAR,AR / VR,null,104551,NaN,<NA>,NaN,NaN,NaN,8903197,0.00
9,other_development_areas,VARCHAR,AI & Digital Solutions;Analytics,？？？,21994,NaN,<NA>,NaN,NaN,NaN,8903197,0.00
10,industry_segment_vertical,VARCHAR,AEC,Telecommunications,23,NaN,<NA>,NaN,NaN,NaN,8903197,0.00
11,other_industry_segment_vertical,VARCHAR,Clinical Medicine,～,38294,NaN,<NA>,NaN,NaN,NaN,8903197,0.02
12,sub_industry_segment_vertical,VARCHAR,Gaming,null,2,NaN,<NA>,NaN,NaN,NaN,8903197,0.00
13,fields_of_interest,VARCHAR,null,null,1,NaN,<NA>,NaN,NaN,NaN,8903197,0.00
14,other_fields_of_interest,VARCHAR,null,null,1,NaN,<NA>,NaN,NaN,NaN,8903197,0.00
15,first_program_application_date,TIMESTAMP,2013-02-01 00:00:00,2026-03-13 12:54:48,6539660,2023-09-25 11:47:31.386649,<NA>,2022-04-19 15:16:47.827913,2024-02-01 17:44:26.870778,2025-03-27 21:10:53.717436,8903197,29.05
16,account_id,VARCHAR,1,9999,33676,NaN,<NA>,NaN,NaN,NaN,8903197,0.00
17,account_name,VARCHAR,#paid,株式会社LINK,34430,NaN,<NA>,NaN,NaN,NaN,8903197,0.00
18,last_activity_date,TIMESTAMP,2002-05-13 04:09:08,2026-03-13 12:54:48,5402204,2023-12-12 07:40:16.68538,<NA>,2022-09-22 04:48:35.090107,2024-06-01 10:33:43.538673,2025-05-20 03:27:19.114646,8903197,17.97
19,last_modified_date,TIMESTAMP,2021-01-30 01:07:18,2026-03-13 13:30:09.485,4938282,2024-11-17 05:16:58.804106,<NA>,2024-04-29 20:08:16.647124,2025-01-07 00:16:26.950721,2025-06-25 09:16:15.572882,8903197,0.00
20,created_date,TIMESTAMP,2020-01-01 00:12:28,2026-03-13 13:30:09.485,7451428,2023-09-12 09:03:09.309979,<NA>,2022-02-25 23:04:45.404371,2024-01-28 06:02:47.071914,2025-03-07 18:15:41.280676,8903197,0.00
21,wwfo_category,VARCHAR,Automotive,null,21,NaN,<NA>,NaN,NaN,NaN,8903197,0.00
22,wwfo_target_list,VARCHAR,Auto_DC_P1,null,91,NaN,<NA>,NaN,NaN,NaN,8903197,0.00
23,account_industry_segment,VARCHAR,null,null,1,NaN,<NA>,NaN,NaN,NaN,8903197,0.00
24,account_source,VARCHAR,Fortune 500: 2021;Forbes Global 2000;Fortune ...,null,409,NaN,<NA>,NaN,NaN,NaN,8903197,0.00
25,account_type,VARCHAR,Enterprise,University,6,NaN,<NA>,NaN,NaN,NaN,8903197,68.01
26,devzone_last_login_date,TIMESTAMP,2011-05-10 19:44:11,2026-03-13 06:24:30,4604368,2023-09-17 06:35:36.974048,<NA>,2022-06-02 22:45:59.432559,2023-12-22 09:18:51.259997,2025-03-02 20:32:50.862896,8903197,49.65
27,organization_website,VARCHAR,-,zzuli.edu.cn,34794,NaN,<NA>,NaN,NaN,NaN,8903197,0.00
28,inception_id,VARCHAR,0011W00001qfUruQAE,null,26224,NaN,<NA>,NaN,NaN,NaN,8903197,0.00
29,first_activity_date,TIMESTAMP,2001-06-08 17:15:40.153,2026-03-13 12:54:48,4092687,2023-08-30 10:27:56.053815,<NA>,2022-03-30 06:51:59.472979,2024-02-18 05:10:20.182808,2025-03-19 13:18:04.274095,8903197,17.97
30,normalized_account_name,VARCHAR,#paid,株式会社LINK,34430,NaN,<NA>,NaN,NaN,NaN,8903197,0.00
31,rdp_exit_date,TIMESTAMP,2025-04-07 18:49:44,2026-03-11 12:20:10,105,2025-09-20 07:59:18.704762,<NA>,2025-07-04 21:12:57.5,2025-09-01 03:29:13,2025-12-11 14:00:07,8903197,100.00

In [15]:
# Check duplicates (replace with primary key if known)
display(con.execute("""
SELECT 
    COUNT(*) AS total_rows,
    COUNT(*) - (
        SELECT COUNT(*)
        FROM (SELECT DISTINCT * FROM contact_clean)
    ) AS duplicate_rows
FROM contact_clean
""").fetchdf())

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   total_rows  duplicate_rows
0     8903197               0

### Analysis for `DEVPM_8674_Cal_Poly_Export_sdk_download.csv`

In [16]:
con.execute("SELECT COUNT(*) FROM sdk_download_clean").fetchdf()

   count_star()
0      93038213

In [17]:
con.execute("""SELECT column_name
FROM information_schema.columns
WHERE table_name = 'sdk_download_raw'""").fetchdf()

        column_name
0            source
1          sdk_name
2       PRODUCTNAME
3    PRODUCTRELEASE
4           country
5            region
6         subregion
7         territory
8              zone
9      downloaddate
10         FILETYPE
11  OPERATINGSYSTEM
12  OS_DISTRIBUTION
13     ARCHITECTURE
14              KPI
15    downloadcount

In [18]:
con.execute("SUMMARIZE sdk_download_clean").fetchdf()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,column_name,column_type,min,max,approx_unique,avg,std,q25,q50,q75,count,null_percentage
0,source,VARCHAR,CDN,VSCODE,13,NaN,NaN,NaN,NaN,NaN,93038213,0.00
1,sdk_name,VARCHAR,3DGRUT,tensorflow_products,218,NaN,NaN,NaN,NaN,NaN,93038213,1.37
2,product_name,VARCHAR,(Linux) Acoustic Echo Cancellation,warp-lang,1183,NaN,NaN,NaN,NaN,NaN,93038213,0.00
3,product_release,VARCHAR,0.0,zjyu7g90o5jt/cosmos-1-0-diffusion-7b-text2worl...,11842,NaN,NaN,NaN,NaN,NaN,93038213,1.39
4,country,VARCHAR,AD,ZW,294,NaN,NaN,NaN,NaN,NaN,93038213,1.35
5,region,VARCHAR,APAC,NALA,3,NaN,NaN,NaN,NaN,NaN,93038213,1.35
6,subregion,VARCHAR,Africa,US & Canada,12,NaN,NaN,NaN,NaN,NaN,93038213,1.35
7,territory,VARCHAR,AFRICA,UK_NORDICS,17,NaN,NaN,NaN,NaN,NaN,93038213,42.43
8,zone,VARCHAR,ANZ,Western Europe,20,NaN,NaN,NaN,NaN,NaN,93038213,1.35
9,download_date,DATE,2020-01-01,2026-03-12,2293,2024-05-01 18:07:15.390675,NaN,2023-06-08,2024-10-09,2025-07-25,93038213,0.00
10,file_type,VARCHAR,?,whl,68,NaN,NaN,NaN,NaN,NaN,93038213,1.29
11,operating_system,VARCHAR,AIX,z/OS,230,NaN,NaN,NaN,NaN,NaN,93038213,19.29
12,os_distribution,VARCHAR,1.0,wsl-ubuntu,211,NaN,NaN,NaN,NaN,NaN,93038213,94.56
13,architecture,VARCHAR,ARM,x86_64,15,NaN,NaN,NaN,NaN,NaN,93038213,94.74
14,kpi,DOUBLE,0.0,1.0,2,0.9604637287188103,0.19486701862207662,1.0,1.0,1.0,93038213,1.00
15,download_count,BIGINT,-449443,7589612,85236,164.80492418037738,5023.858590067907,1,2,8,93038213,0.00

In [19]:
# Check duplicates (replace with primary key if known)
display(con.execute("""
SELECT 
    COUNT(*) AS total_rows,
    COUNT(*) - (
        SELECT COUNT(*)
        FROM (SELECT DISTINCT * FROM sdk_download_clean)
    ) AS duplicate_rows
FROM sdk_download_clean
""").fetchdf())

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   total_rows  duplicate_rows
0    93038213          275400