In [23]:
import duckdb
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

DB_PATH = "developer_project.duckdb"
con = duckdb.connect(DB_PATH)

pd.set_option("display.max_columns", 200)
pd.set_option("display.max_rows", 100)

ACTIVITY_TABLE = "activity_final"
CONTACT_TABLE = "contact_final"

In [24]:
con.execute("""SHOW TABLES""").fetchdf()

                                      name
0                            activity_base
1                           activity_clean
2                     activity_enriched_v1
3                           activity_final
4                     activity_ontology_v1
5                             activity_raw
6             activity_score_mapping_clean
7               activity_score_mapping_raw
8                            activity_work
9                  calendar_30d_periods_v1
10                           contact_clean
11  contact_clean_backup_before_supplement
12                           contact_final
13                             contact_raw
14                contact_supplement_clean
15                  contact_supplement_raw
16                            contact_work
17                       dev_activation_v1
18          dev_asof_features_30_90_180_v1
19                    dev_dormancy_base_v1
20      dev_dormancy_holdout_validation_v1
21                  dev_dormancy_status_v1
22                    dev_features_180d_v1
23                     dev_features_30d_v1
24                     dev_features_90d_v1
25                dev_features_curr_30d_v1
26                dev_features_lifetime_v1
27                dev_features_prev_30d_v1
28             dev_longitudinal_summary_v1
29      dev_meaningful_return_intervals_v1
30                  dev_meaningful_week_v1
31              dev_period_30d_features_v1
32               dev_period_30d_profile_v1
33           dev_period_30d_transitions_v1
34              dev_period_activity_30d_v1
35            dev_period_profile_sample_v1
36                   dev_period_profile_v1
37               dev_period_transitions_v1
38                 dev_persona_lifetime_v1
39                          dev_persona_v1
40                     dev_profile_180d_v1
41                      dev_profile_30d_v1
42                      dev_profile_90d_v1
43                 dev_profile_curr_30d_v1
44                    dev_profile_final_v1
45                    dev_profile_final_v2
46                    dev_profile_final_v3
47                 dev_profile_prev_30d_v1
48                          dev_profile_v1
49                       dev_transition_v1
50                  dev_weekly_features_v1
51                   developer_universe_v1
52                      km_return_curve_v1
53                      sdk_download_clean
54                      sdk_download_final
55                        sdk_download_raw
56                                sdk_work

In [25]:
con.execute("""
SELECT
    persona,
    COUNT(*) AS cnt,
    COUNT(*) * 1.0 / SUM(COUNT(*)) OVER () AS pct
FROM dev_persona_v1
GROUP BY 1
ORDER BY cnt DESC
""").fetchdf()

              persona      cnt       pct
0                CUDA  3284784  0.350134
1               GenAI  2466314  0.262891
2             Unknown  2077710  0.221469
3          Simulation   730837  0.077902
4            Robotics   586379  0.062504
5  Learning_Community   235484  0.025101

In [26]:
con.execute("""
SELECT COUNT(*)
FROM dev_features_lifetime_v1
WHERE lifetime_activity_count = 0
""").fetchdf()

   count_star()
0       1721230

In [27]:
con.execute("""
SELECT *
FROM activity_ontology_v1
WHERE persona_hint = 'Other'
LIMIT 100

""").fetchdf()

,developer_id,activity_date,activity,activity_name,activity_type,activity_role,activity_attendance,activity_score,filepath,lead_source,lead_source_details,nvidia_campaign_id,created_date,first_activity_date,last_activity_date,development_areas,fields_of_interest,account_id,account_type,country,region,industry_segment_vertical,program_application_source,organization_english_name,normalized_account_name,wwfo_category,wwfo_target_list,keyword_text,persona_activity_text,persona_profile_text,cuda_activity_score,genai_activity_score,robotics_activity_score,simulation_activity_score,cuda_profile_score,genai_profile_score,robotics_profile_score,simulation_profile_score,journey_signal,effort_level,modality,cuda_persona_raw,genai_persona_raw,robotics_persona_raw,simulation_persona_raw,learning_community_persona_raw,persona_hint,cuda_persona_score,genai_persona_score,robotics_persona_score,simulation_persona_score,learning_community_persona_score,journey_stage_score,effort_score
0,4100351,2022-01-11,dev program membership,developer,approved,unknown,true,1.0,None,ref,ref-blog.csdn.net/weixin_43848614/article/deta...,NaN,2022-01-11 06:39:52,2022-01-11 00:00:00,2023-01-02 00:00:00,data science,null,6561,university,CHINA,apac,hardware / semiconductor,null,Southwest Jiaotong University,Southwest Jiaotong University,null,her target,dev program membership approved unknown true r...,developer ref-blog.csdn.net/weixin_43848614/a...,data science null hardware / semiconductor,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Discover,Passive,Membership,0.0,0.0,0.0,0.0,0.0,Other,0.0,0.0,0.0,0.0,0.0,1,1
1,4100361,2022-01-11,dev program membership,developer,approved,unknown,true,1.0,None,ref,ref-www.so.com/link?m=bmdqt1thuz2oormbww1uobxa...,NaN,2022-01-11 06:47:23,2022-01-11 00:00:00,2022-01-11 06:47:22,ar / vr,null,31153,unknown,CHINA,apac,other,null,suzhou top,Not Normalized,null,null,dev program membership approved unknown true r...,developer ref-www.so.com/link?m=bmdqt1thuz2oo...,ar / vr null other,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Discover,Passive,Membership,0.0,0.0,0.0,0.0,0.0,Other,0.0,0.0,0.0,0.0,0.0,1,1
2,4100491,2022-01-11,dev program membership,developer,approved,unknown,true,1.0,None,ref,ref-docs.nvidia.com/,NaN,2022-01-11 08:43:34,2022-01-11 00:00:00,2022-01-11 08:43:35,data science,null,31153,unknown,GERMANY,emea,other,null,BASF Polyurethanes GmbH,Not Normalized,null,null,dev program membership approved unknown true r...,developer ref-docs.nvidia.com/,data science null other,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Discover,Passive,Membership,0.0,0.0,0.0,0.0,0.0,Other,0.0,0.0,0.0,0.0,0.0,1,1
3,4101656,2022-01-11,dev program membership,developer,approved,unknown,true,1.0,None,gseo,https://www.google.com/,NaN,2022-01-11 20:47:30,2022-01-11 00:00:00,2022-01-11 20:47:30,data center / cloud,null,8784,university,HUNGARY,emea,agriculture,null,University of Electronic Science and Technolog...,University of Electronic Science and Technolog...,higher ed/research,her target,dev program membership approved unknown true g...,developer https://www.google.com/,data center / cloud null agriculture,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Discover,Passive,Membership,0.0,0.0,0.0,0.0,0.0,Other,0.0,0.0,0.0,0.0,0.0,1,1
4,4102258,2022-01-12,dev program membership,developer,approved,unknown,true,1.0,None,gseo,https://www.google.com/,NaN,2022-01-12 06:17:53,2022-01-12 00:00:00,2022-01-12 06:17:55,data science,null,7132,unknown,UNITED STATES,nala,academia / education,null,Penn State,Pennsylvania State University (PSU),null,cryo-em 2019_p1;her target,dev program membership approved unknown true g...,developer https://www.google.com/,data science null academia / education,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Discover,Passive,Membership,0.0,0.0,0.0,0.0,0.0,Other,0.0,0.0,0.0,0.0,0.0,1,1
5,4103247,2022-01-12,dev program membership,developer,approved,unknown,true,1.0,None,gseo,https://www.google.com/,NaN,2022-01-12 16:04:15,2022-01-12 00:00:00,2022-01-12 00:00:00,data science,null,8862,university,UNITED KINGDOM,emea,academia / education,null,Lancaster university,Lancaster University,higher ed/research,her target,dev program membership approved unknown true g...,developer https://www.google.com/,data science null academia / education,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Discover,Passive,Membership,0.0,0.0,0.0,0.0,0.0,Other,0.0,0.0,0.0,0.0,0.0,1,1
6,4051340,2022-01-13,dev program membership,developer,approved,unknown,true,1.0,None,gseo,https://www.google.com/,pa-srch-goog-544428,2022-01-13 02:01:31,2022-01-13 00:00:00,2022-01-13 00:00:00,null,null,7704,unknown,NULL,null,other,null,null,Unclassified - Invalid,null,null,dev program membership approved unknown true g...,developer https://www.google.com/,null null other,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Discover,Passive,Membership,0.0,0.0,0.0,0.0,0.0,Other,0.0,0.0,0.0,0.0,0.0,1,1
7,4104056,2022-01-13,dev program membership,developer,approved,unknown,true,1.0,None,ref,ref-zukaaax.com/,NaN,2022-01-13 04:16:26,2022-01-13 00:00:00,2022-01-13 04:05:56,null,null,7704,unknown,NULL,null,other,null,null,Unclassified - Invalid,null,null,dev program membership approved unknown true r...,developer ref-zukaaax.com/,null null other,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Discover,Passive,Membership,0.0,0.0,0.0,0.0,0.0,Other,0.0,0.0,0.0,0.0,0.0,1,1
8,4104138,2022-01-13,dev program membership,developer,approved,unknown,true,1.0,None,gseo,https://www.google.com/,NaN,2022-01-13 05:46:31,2022-01-13 00:00:00,2022-01-13 05:35:59,null,null,7704,unknown,NULL,null,other,null,null,Unclassified - Invalid,null,null,dev program membership approved unknown true g...,developer https://www.google.com/,null null other,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Discover,Passive,Membership,0.0,0.0,0.0,0.0,0.0,Other,0.0,0.0,0.0,0.0,0.0,1,1
9,4059059,2022-01-13,dev program membership,developer,approved,unknown,true,1.0,None,unknown,unknown,NaN,2022-01-13 06:16:40,2022-01-13 00:00:00,2022-01-13 06:19:28,null,null,7704,unknown,NULL,null,other,null,null,Unclassified - Invalid,null,null,dev program membership approved unknown true u...,developer unknown,null null other,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Discover,Passive,Membership,0.0,0.0,0.0,0.0,0.0,Other,0.0,0.0,0.0,0.0,0.0,1,1
10,4104449,2022-01-13,dev program membership,developer,approved,unknown,true,1.0,None,ref,ref-beuracle77.tistory.com/5,NaN,2022-01-13 08:31:37,2022-01-13 00:00:00,2022-01-19 00:00:00,null,null,7704,unknown,NULL,null,other,null,null,Unclassified - Invalid,null,null,dev program membership approved unknown true r...,developer ref-beuracle77.tistory.com/5,null null other,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Discover,Passive,Membership,0.0,0.0,0.0,0.0,0.0,Other,0.0,0.0,0.0,0.0,0.0,1,1
11,4105388,2022-01-13,dev program membership,developer,approved,unknown,true,1.0,None,website,developer.nvidia.com/rtx/ngx,NaN,2022-01-13 20:01:26,2022-01-13 00:00:00,2022-01-16 11:52:54,null,null,7704,unknown,NULL,null,other,null,null,Unclassified - Invalid,null,null,dev program membership approved unknown true w...,developer developer.nvidia.com/rtx/ngx,null null other,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Discover,Passive,Membership,0.0,0.0,0.0,0.0,0.0,Other,0.0,0.0,0.0,0.0,0.0,1,1
12,4105397,2022-01-13,dev program membership,developer,approved,unknown,true,1.0,None,unknown,unknown,NaN,2022-01-13 20:16:19,2022-01-13 00:00:00,2022-01-13 00:00:00,null,null,7704,unknown,NULL,null,other,null,null,Unclassified - Invalid,null,null,dev program membership approved unknown true u...,developer unknown,null null other,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Discover,Passive,Membership,0.0,0.0,0.0,0.0,0.0,Other,0.0,0.0,0.0,0.0,0.0,1,1
13,4105489,2022-01-13,dev program membership,developer,approved,unknown,true,1.0,None,ref,ref-docs.nvidia.com/,NaN,2022-01-13 21:46:19,2022-01-13 00:00:00,2022-01-13 21:42:41,null,null,7704,unknown,NULL,null,other,null,null,Unclassified - Invalid,null,null,dev program membership approved unknown true r...,developer ref-docs.nvidia.com/,null null other,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Discover,Passive,Membership,0.0,0.0,0.0,0.0,0.0,Other,0.0,0.0,0.0,0.0,0.0,1,1
14,4106138,2022-01-14,dev program membership,developer,approved,unknown,true,1.0,None,gseo,https://www.google.com/,NaN,2022-01-14 07:01:31,2022-01-14 00:00:00,2022-01-14 07:00:19,null,null,7704,unknown,NULL,null,other,null,null,Unclassified - Invalid,null,null,dev program membership approved unknown true g...,developer https://www.google.com/,null null other,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Discover,Passive,Membership,0.0,0.0,0.0,0.0,0.0,Other,0.0,0.0,0.0,0.0,0.0,1,1
15,4106281,2022-01-14,dev program membership,developer,approved,unknown,true,1.0,None,ref,ref-blog.csdn.net/jhsignal/article/details/111...,NaN,2022-01-14 08:16:35,2022-01-14 00:00:00,2022-01-14 08:31:13,null,null,7704,unknown,NULL,null,other,null,null,Unclassified - Invalid,null,null,dev program membership approved unknown true r...,developer ref-blog.csdn.net/jhsignal/article/...,null null other,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Discover,Passive,Membership,0.0,0.0,0.0,0.0,0.0,Other,0.0,0.0,0.0,0.0,0.0,1,1
16,4106736,2022-01-14,dev program membership,developer,approved,unknown,true,1.0,None,unknown,unknown,NaN,2022-01-14 13:31:32,2022-01-14 00:00:00,2022-01-14 00:00:00,null,null,7704,unknown,NULL,null,other,null,null,Unclassified - Invalid,null,null,dev program membership approved unknown true u...,developer unknown,null null other,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Discover,Passive,Membership,0.0,0.0,0.0,0.0,0.0,Other,0.0,0.0,0.0,0.0,0.0,1,1
17,4106900,2022-01-14,dev program membership,developer,approved,unknown,true,1.0,None,ref,ref-www.nvidia.com/,NaN,2022-01-14 15:16:29,2022-01-14 00:00:00,2022-01-14 00:00:00,null,null,7704,unknown,NULL,null,other,null,null,Unclassified - Invalid,null,null,dev program membership approved unknown true r...,developer ref-www.nvidia.com/,null null other,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Discover,Passive,Membership,0.0,0.0,0.0,0.0,0.0,Other,0.0,0.0,0.0,0.0,0.0,1,1
18,4107854,2022-01-15,dev program membership,developer,approved,unknown,true,1.0,None,ref,ref-www.reddit.com/,NaN,2022-01-15 06:45:50,2022-01-15 00:00:00,2022-01-23 00:00:00,data science;networking / communications,null,31153,unknown,AUSTRALIA,apac,academia / education,null,dandenong high school,Not Normalized,null,null,dev program membership approved unknown true r...,developer ref-www.reddit.com/,data science;networking / communications null ...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Discover,Passive,Membership,0.0,0.0,0.0,0.0,0.0,Other,0.0,0.0,0.0,0.0,0.0,1,1
19,4107858,2022-01-15,dev program membership,developer,approved,unknown,true,1.0,None,gseo,https://www.google.com/,NaN,2022-01-15 07:12:05,2022-01-15 00:00:00,2022-01-21 00:00:00,data science;networking / communications,null,7704,unknown,"KOREA, REPUBLIC OF",apac,other,null,SSWU,Unclassified - Invalid,null,null,dev program membership approved unknown true g...,developer https://www.google.com/,data science;networking / communications null ...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Discover,Passive,Membership,0.0,0.0,0.0,0.0,0.0,Other,0.0,0.0,0.0,0.0,0.0,1,1
20,4108102,2022-01-15,dev program membership,developer,approved,unknown,true,1.0,None,gseo,https://www.google.com/,NaN,2022-01-15 09:53:05,2022-01-15 00:00:00,2022-01-15 09:53:03,data science,null,31153,unknown,GERMANY,emea,academia / education,null,THM Business School,Not Normalized,null,null,dev program membership approved unknown true g...,developer https://www.google.com/,data science null academia / education,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Discover,Passive,Membership,0.0,0.0,0.0,0.0,0.0,Other,0.0,0.0,0.0,0.0,0.0,1,1
21,4108110,2022-01-15,dev program membership,developer,approved,unknown,true,1.0,None,ref,ref-www.youtube.com/,NaN,2022-01-15 12:49:05,2022-01-15 00:00:00,2022-01-15 12:49:05,ar / vr,null,1498,university,EGYPT,emea,energy,null,Egypt Japan University Of Science And Technolo...,Egypt Japan University Of Science And Technolo...,null,null,dev program membership approved unknown true r...,developer ref-www.youtube.com/,ar / vr null energy,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Discover,Passive,Membership,0.0,0.0,0.0,0.0,0.0,Other,0.0,0.0,0.0,0.0,0.0,1,1
22,4108647,2022-01-15,dev program membership,developer,approved,unknown,true,1.0,None,gseo,https://www.google.com/,NaN,2022-01-15 17:16:17,2022-01-15 00:00:00,2022-06-21 00:00:00,data science,null,1028,university,ITALY,emea,other,null,Catholic University of the Sacred Heart,Università Cattolica Del Sacro Cuore,null,her target,dev program membership approved unknown true g...,developer https://www.google.com/,data science null other,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Discover,Passive,Membership,0.0,0.0,0.0,0.0,0.0,Other,0.0,0.0,0.0,0.0,0.0,1,1
23,4108706,2022-01-15,dev program membership,developer,approved,unknown,true,1.0,None,unknown,unknown,NaN,2022-01-15 18:56:44,2022-01-15 00:00:00,2022-01-15 00:00:00,networking / communications,null,31153,unknown,UNITED KINGDOM,emea,other,null,Gweilo inc.,Not Normalized,null,null,dev program membership approved unknown true u...,developer unknown,networking / communications null other,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Discover,Passive,Membership,0.0,0.0,0.0,0.0,0.0,Other,0.0,0.0,0.0,0.0,0.0,1,1
24,4108778,2022-01-15,dev program membership,developer,approved,unknown,true,1.0,None,ref,ref-bitbucket.org/,NaN,2022-01-15 19:08:43,2022-01-15 00:00:00,2022-01-15 00:00:00,data science,null,7727,unknown,GERMANY,emea,agriculture,null,Abc,Unclassified - Acronym,null,null,dev program membership approved unknown true r...,developer ref-bitbucket.org/,data science null agriculture,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Discover,Passive,Membership,0.0,0.0,0.0,0.0,0.0,Other,0.0,0.0,0.0,0.0,0.0,1,1
25,4109386,2022-01-16,dev program membership,developer,approved,unknown,true,1.0,None,unknown,unknown,NaN,2022-01-16 07:10:32,2022-01-16 07:11:27,2022-02-06 00:00:00,ar / vr,null,3221,unknown,CHINA,apac,aec,null,DD Studio,Dd Studio,null,null,dev program membership approved unknown true u...,developer unknown,ar / vr null aec,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Discover,Passive,Membership,0.0,0.0,0.0,0.0,0.0,Other,0.0,0.0,0.0,0.0,0.0,1,1
26,4110591,2022-01-17,dev program membership,developer,approved,unknown,true,1.0,None,ref,ref-www.baidu.com/link?url=t5t8nqqgqxvks_6hifg...,NaN,2022-01-17 01:43:13,2022-01-17 00:00:00,2022-01-17 01:43:42,ar / vr,null,7704,unknown,CHINA,apac,other,null,11,Unclassified - Invalid,null,null,dev program membership approved unknown true r...,developer ref-www.baidu.com/link?url=t5t8nqqg...,ar / vr null other,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Discover,Passive,Membership,0.0,0.0,0.0,0.0,0.0,Other,0.0,0.0,0.0,0.0,0.0,1,1
27,3792374,2022-01-17,dev program membership,developer,approved,unknown,true,1.0,None,gseo,https://www.google.com/,NaN,2021-12-30 13:15:01,2022-01-17 00:00:00,2022-01-17 02:26:12,data science;ar / vr;networking / communications,null,2592,unknown,"KOREA, REPUBLIC OF",apac,other,null,EWHA WOMANS UNIVERSITY,Ewha Womans University,higher ed/research,her target,dev program membership approved unknown true g...,developer https://www.google.com/,data science;ar / vr;networking / communicatio...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Discover,Passive,Membership,0.0,0.0,0.0,0.0,0.0,Other,0.0,0.0,0.0,0.0,0.0,1,1
28,4112815,2022-01-18,dev program membership,developer,approved,unknown,true,1.0,None,gseo,https://www.google.com/,NaN,2022-01-18 06:13:40,2022-01-18 00:00:00,2022-01-18 06:13:40,data science,null,7704,unknown,CANADA,nala,other,null,-,Unclassified - Invalid,null,null,dev program membership approved unknown true g...,developer https://www.google.com/,data science null other,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Discover,Passive,Membership,0.0,0.0,0.0,0.0,0.0,Other,0.0,0.0,0.0,0.0,0.0,1,1
29,4113392,2022-01-18,dev program membership,developer,approved,unknown,true,1.0,None,gseo,https://www.google.com/,NaN,2022-01-18 11:56:46,2022-01-18 00:00:00,2022-01-19 00:00:00,data center / cloud,null,6709,enterprise,INDONESIA,apac,other,null,Walt Disney,Walt Disney,null,null,dev program membership approved unknown true g...,developer https://www.google.com/,data center / cloud null other,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Discover,Passive,Membership,0.0,0.0,0.0,0.0,0.0,Other,0.0,0.0,0.0,0.0,0.0,1,1
30,4114498,2022-01-19,dev program membership,developer,approved,unknown,true,1.0,None,gseo,https://www.google.com/,NaN,2022-01-19 03:11:14,2022-01-19 00:00:00,2022-01-19 00:00:00,ar / vr,null,2649,enterprise,CHINA,apac,other,null,Amd,Advanced Micro Devices,null,null,dev program membership approved unknown true g...,developer https://www.google.com/,ar / vr null other,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Discover,Passive,Membership,0.0,0.0,0.0,0.0,0.0,Other,0.0,0.0,0.0,0.0,0.0,1,1
31,4115408,2022-01-19,dev program membership,developer,approved,unknown,true,1.0,None,gseo,https://www.google.com/,NaN,2022-01-19 12:07:23,2022-01-19 00:00:00,2022-01-19 12:07:40,data science,null,7620,university,GREECE,emea,other,null,NATIONAL TECHNICAL UNIVERSITY OF ATHENS,National Technical University Of Athens,null,her target,dev program membership approved unknown true g...,developer https://www.google.com/,data science null other,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Discover,Passive,Membership,0.0,0.0,0.0,0.0,0.0,Other,0.0,0.0,0.0,0.0,0.0,1,1
32,5912121,2022-01-19,dev program membership,developer,approved,unknown,true,1.0,None,unknown,unknown,NaN,2022-01-19 17:36:29,2022-01-19 00:00:00,2025-11-28 18:51:10,data science;networking / communications;data ...,null,31153,unknown,INDIA,apac,cloud services,devzone,Bengal College O Engineering And Technology,Not Normalized,null,null,dev program membership approved unknown true u...,developer unknown,data science;networking / communications;data ...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Discover,Passive,Membership,0.0,0.0,0.0,0.0,0.0,Other,0.0,0.0,0.0,0.0,0.0,1,1
33,4116257,2022-01-19,dev program membership,developer,approved,unknown,true,1.0,None,gseo,https://www.google.com/,NaN,2022-01-19 20:46:36,2022-01-19 00:00:00,2023-03-21 00:00:00,data science;networking / communications;other,null,7555,university,GERMANY,emea,healthcare & life sciences,gtc fall 2022,Johannes Gutenberg University Mainz,Johannes Gutenberg University Mainz,higher ed/research,her target,dev program membership approved unknown true g...,developer https://www.google.com/,data science;networking / communications;other...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Discover,Passive,Membership,0.0,0.0,0.0,0.0,0.0,Other,0.0,0.0,0.0,0.0,0.0,1,1
34,4116610,2022-01-20,dev program membership,developer,approved,unknown,true,1.0,None,ref,ref-www.baidu.com/link?url=ccgn1ey983h-exsxdbf...,NaN,2022-01-20 02:47:10,2022-01-20 00:00:00,2022-01-20 00:00:00,ar / vr,null,7771,unknown,CHINA,apac,gaming,null,YOUTUBE,YouTube,null,null,dev program membership approved unknown true r...,developer ref-www.baidu.com/link?url=ccgn1ey9...,ar / vr null gaming,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Discover,Passive,Membership,0.0,0.0,0.0,0.0,0.0,Other,0.0,0.0,0.0,0.0,0.0,1,1
35,4117059,2022-01-20,dev program membership,developer,approved,unknown,true,1.0,None,gseo,https://www.google.com/,NaN,2022-01-20 07:04:13,2022-01-20 00:00:00,2022-01-20 00:00:00,data science,null,31153,unknown,RUSSIAN FEDERATION,emea,other,null,RT MIS,Not Normalized,null,null,dev program membership approved unknown true g...,developer https://www.google.com/,data science null other,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Discover,Passive,Membership,0.0,0.0,0.0,0.0,0.0,Other,0.0,0.0,0.0,0.0,0.0,1,1

In [28]:
con.execute("""
SELECT activity, COUNT(*)
FROM activity_ontology_v1
WHERE persona_hint = 'Other'
GROUP BY 1
ORDER BY COUNT(*) DESC

""").fetchdf()

                  activity  count_star()
0   dev program membership       1084495
1            ngc downloads        708369
2        devzone downloads        273065
3          on-demand views        148075
4                model api        128099
5                     brev         24638
6     program applications         22512
7               bugs filed         22383
8            user feedback         12086
9   product specific comms         10877
10     event registrations          3045
11                contests           760
12              hackathons           699

In [29]:
con.execute("""
SELECT
    activity_name,
    COUNT(*) AS cnt
FROM activity_ontology_v1
WHERE persona_hint = 'Other'
GROUP BY 1
ORDER BY cnt DESC
LIMIT 50

""").fetchdf()

                                        activity_name      cnt
0                                           developer  1063556
1                                               other   334624
2                                             unknown   282513
3                                          sdkmanager    88213
4                                          ai-qwq-32b    77342
5                                                misc    26288
6                                                doca    13432
7                                              shield    10007
8                                   codeworks android     9365
9                                   nvidia reflex sdk     7892
10               nvidia driver manager for kubernetes     7495
11                                           rivermax     7249
12                                      ai-embed-qa-4     6242
13                                             ubuntu     6146
14                                micro opt-in (dlss)     5871
15                                       segmentation     5362
16                                                gtc     5318
17  nvidia optimized deep learning framework power...     5166
18                                         shield ota     5084
19                               doca sdk access form     4490
20                                                nlp     4359
21                                ai-nv-embedqa-e5-v5     4350
22                                        recommender     4347
23                             micro opt-in (hpc sdk)     4252
24                     doca sdk early access (closed)     4197
25         [gtc digital spring 2023] gtc 2023 keynote     3976
26                                   awesome-gpu-name     3321
27                                                fcd     3309
28                                micro opt-in (doca)     3175
29                                      nvidia reflex     3135
30                   maxine sdk early access (closed)     3018
31                         nvidia vgpu guest driver 4     2998
32                              semantic segmentation     2847
33           maxine sdk early access application form     2819
34                                          photoshop     2750
35  [gtc digital april 2021] rethinking drug disco...     2748
36                                  nvcc cleanup tool     2648
37                         display mode selector tool     2600
38                             nvdev-nv-embedqa-e5-v5     2519
39                                            gromacs     2475
40  [gtc digital april 2021] human-inspired induct...     2175
41                     [gtc 24 2024] gtc 2024 keynote     2138
42                            nvidia network operator     2070
43                                          ai-bge-m3     2056
44             display mode selector tool access form     2043
45  transfer learning toolkit for video streaming ...     2041
46              cloudxr sdk - registered program form     2035
47                                     nvidia hpc sdk     2011
48                           cloudxr sdk - registered     1989
49                                         av-product     1986

In [30]:
con.execute("""
SELECT
    filepath,
    COUNT(*) AS cnt
FROM activity_ontology_v1
WHERE persona_hint = 'Other'
GROUP BY 1
ORDER BY cnt DESC
LIMIT 50
""").fetchdf()

                                             filepath      cnt
0                                                 NaN  1323887
1                ad2a0a99-910d-448f-8006-2eb942b3b9f2    77342
2   /assets/secure/shadermodel6-9-preview-driver/5...    25626
3              nvidia/maxine/maxine_windows_ar_sdk_ga    22575
4   verizon://sdkmanager/secure/clients/sdkmanager...    14677
5   verizon://sdkmanager/secure/clients/sdkmanager...    11917
6   /sdkmanager/secure/clients/sdkmanager-2.2.0.12...    10637
7   /sdkmanager/secure/clients/sdkmanager-2.3.0.12...     7399
8     /nvidia-reflex-sdk/secure/Nvidia_Reflex_SDK.zip     7250
9   /sdkmanager/secure/clients/sdkmanager-2.3.0.12...     6775
10               09c64e32-2b65-4892-a285-2f585408d118     6242
11  verizon://assets/mobile/secure/codeworks-andro...     5259
12  /sdkmanager/secure/clients/sdkmanager-1.9.2.10...     4652
13               303d34cf-7ebf-41ee-a1d8-e07e8ba2d4e7     4350
14  /sdkmanager/secure/clients/sdkmanager-2.0.0.11...     4342
15                         nvidian/sshfs_lookup_table     3995
16  /sdkmanager/secure/clients/sdkmanager-2.2.0.12...     3852
17  nvidia/maxine/maxine_windows_video_effects_sdk_ga     3816
18  /sdkmanager/secure/clients/sdkmanager-1.9.3.10...     3701
19                            nvidia/base/ubuntu:null     3255
20  /sdkmanager/secure/clients/sdkmanager-2.4.0.13...     2945
21  /sdkmanager/secure/clients/sdkmanager-1.9.1.10...     2849
22  /tools/files/Photoshop_Plugins_x64_8.55.0109.1...     2739
23  /sdkmanager/secure/clients/sdkmanager-2.1.0.11...     2648
24       /assets/secure/nvcc/CleanupTool_1.0.20.0.exe     2648
25               557bdefd-143a-4871-98c8-c8f36f0c3f03     2519
26  verizon://assets/secure/reflex/Nvidia_Reflex_S...     2470
27        nvidia/cloud-native/k8s-driver-manager:null     2407
28  /sdkmanager/secure/clients/sdkmanager-2.3.0.12...     2357
29              nvstaging/doca/doca_container_configs     2337
30  /sdkmanager/secure/clients/sdkmanager-2.3.0.12...     2281
31  /sdkmanager/secure/clients/sdkmanager-2.0.0.11...     2193
32               6acccd83-8f46-42b2-a191-529be72bb8de     2056
33  /sdkmanager/secure/clients/sdkmanager-2.1.0.11...     2032
34                                  nvidia/nvhpc:null     1920
35  /sdkmanager/secure/clients/sdkmanager-2.1.0.11...     1877
36               6497fc2b-7ff8-4019-8946-123dccbfc863     1845
37                                          nvegx/eac     1835
38                                      nvegx/egx-krs     1830
39                               nvegx/egx-fluent-bit     1823
40                nvstaging/mellanox/network-operator     1796
41                                     nvegx/gpuagent     1779
42                         eevaigoeixww/staging/redis     1729
43              eevaigoeixww/staging/redis-timeseries     1728
44            nvidia/base/ubuntu:20.04_x64_2022-09-23     1724
45                   eevaigoeixww/staging/ucf_svc_vms     1669
46  nvidia/maxine/maxine_windows_audio_effects_sdk_ga     1575
47                       eevaigoeixww/staging/mongodb     1574
48               bc205f8e-1740-40df-8d32-c4321763498a     1555
49                           eevaigoeixww/staging/vms     1513

In [31]:
con.execute("""
SELECT
    AVG(total_persona_score),
    MIN(total_persona_score),
    MAX(total_persona_score)
FROM dev_persona_v1
""").fetchdf()

,avg(total_persona_score),min(total_persona_score),max(total_persona_score)
0,111.80916,0.0,32940193.0

In [32]:
con.execute("""
SELECT
    activity_name,
    COUNT(*) AS cnt
FROM activity_ontology_v1
WHERE persona_hint = 'Other'
GROUP BY 1
ORDER BY cnt DESC
LIMIT 100
""").fetchdf()

                                        activity_name      cnt
0                                           developer  1063556
1                                               other   334624
2                                             unknown   282513
3                                          sdkmanager    88213
4                                          ai-qwq-32b    77342
5                                                misc    26288
6                                                doca    13432
7                                              shield    10007
8                                   codeworks android     9365
9                                   nvidia reflex sdk     7892
10               nvidia driver manager for kubernetes     7495
11                                           rivermax     7249
12                                      ai-embed-qa-4     6242
13                                             ubuntu     6146
14                                micro opt-in (dlss)     5871
15                                       segmentation     5362
16                                                gtc     5318
17  nvidia optimized deep learning framework power...     5166
18                                         shield ota     5084
19                               doca sdk access form     4490
20                                                nlp     4359
21                                ai-nv-embedqa-e5-v5     4350
22                                        recommender     4347
23                             micro opt-in (hpc sdk)     4252
24                     doca sdk early access (closed)     4197
25         [gtc digital spring 2023] gtc 2023 keynote     3976
26                                   awesome-gpu-name     3321
27                                                fcd     3309
28                                micro opt-in (doca)     3175
29                                      nvidia reflex     3135
30                   maxine sdk early access (closed)     3018
31                         nvidia vgpu guest driver 4     2998
32                              semantic segmentation     2847
33           maxine sdk early access application form     2819
34                                          photoshop     2750
35  [gtc digital april 2021] rethinking drug disco...     2748
36                                  nvcc cleanup tool     2648
37                         display mode selector tool     2600
38                             nvdev-nv-embedqa-e5-v5     2519
39                                            gromacs     2475
40  [gtc digital april 2021] human-inspired induct...     2175
41                     [gtc 24 2024] gtc 2024 keynote     2138
42                            nvidia network operator     2070
43                                          ai-bge-m3     2056
44             display mode selector tool access form     2043
45  transfer learning toolkit for video streaming ...     2041
46              cloudxr sdk - registered program form     2035
47                                     nvidia hpc sdk     2011
48                           cloudxr sdk - registered     1989
49                                         av-product     1986
50                                    doca base image     1881
51                                        sdk manager     1847
52                        ai-jamba-1_5-large-instruct     1845
53                                           cutensor     1841
54                                         unassigned     1836
55  [gtc digital april 2021] modern artificial int...     1759
56                                                ace     1738
57                                            cloudxr     1719
58  [gtc digital april 2021] transforming the auto...     1657
59                                             golang     1629
60                                        ai-neva-22b     1555
61                                idc6_partner_issues     1527
62                             doca telemetry service     1520
63                                      ai-phi-3-mini     1490
64   [gtc digital april 2021] how gpu computing works     1470
65                                  re-identification     1457
66          [gtc digital april 2021] gtc 2021 keynote     1440
67                                     ai-nv-embed-v1     1391
68                                              clara     1378
69                                   optical flow sdk     1372
70  [gtc digital april 2021] realizing the vision ...     1367
71         [gtc digital spring 2022] gtc 2022 keynote     1363
72                                edify-customization     1340
73                      china developer day 2025 form     1326
74                                 content_generation     1301
75                                               ldat     1268
76                                     dialog-manager     1265
77                                            modulus     1264
78                                             simnet     1253
79                                                jax     1251
80                                  dli teaching kits     1235
81               maxine early access application form     1222
82                                            nvshmem     1219
83                                     clara holoscan     1205
84                              dli teaching kit form     1191
85                                         aerial sdk     1184
86                                         vmaterials     1183
87                                             python     1177
88                                maxine early access     1168
89                                              kaldi     1163
90                                      maxine survey     1139
91                                 holoscan container     1134
92                                          rtx voice     1109
93                         kubevirt gpu device plugin     1081
94                                  nvidia parabricks     1071
95                                             chroma     1067
96  [gtc digital april 2021] a new africa and a ne...     1063
97                      optical character recognition     1049
98                                    clara train sdk     1046
99                              av-product definition     1039

In [33]:
con.close()